"""empty message

Revision ID: 1dfb3b1dedb0
Revises: d46823402ce0
Create Date: 2020-04-25 13:13:23.187052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfb3b1dedb0'
down_revision = 'd46823402ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('License',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.LargeBinary(), nullable=True),
    sa.Column('license_key', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('License')
    op.drop_table('Activity')
    # ### end Alembic commands ###
