"""empty message

Revision ID: 688f98c398ff
Revises: aeb23ab87423
Create Date: 2020-04-23 09:08:41.066717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688f98c398ff'
down_revision = 'aeb23ab87423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['phone'])
    op.create_unique_constraint(None, 'User', ['username'])
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    # ### end Alembic commands ###
