"""empty message

Revision ID: aeb23ab87423
Revises: c9704dba2b7e
Create Date: 2020-04-23 06:30:17.137859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb23ab87423'
down_revision = 'c9704dba2b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('appCode', sa.String(), nullable=True))
    op.add_column('User', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(), nullable=True))
    op.add_column('User', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('password', sa.String(), nullable=True))
    op.add_column('User', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('User', sa.Column('username', sa.String(), nullable=True))
    op.add_column('User', sa.Column('verified', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('verify_code', sa.Integer(), nullable=True))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'verify_code')
    op.drop_column('User', 'verified')
    op.drop_column('User', 'username')
    op.drop_column('User', 'phone')
    op.drop_column('User', 'password')
    op.drop_column('User', 'modified')
    op.drop_column('User', 'last_login')
    op.drop_column('User', 'failed_attempts')
    op.drop_column('User', 'email')
    op.drop_column('User', 'created')
    op.drop_column('User', 'appCode')
    # ### end Alembic commands ###
