"""empty message

Revision ID: b2e019922d64
Revises: ba9443cb4078
Create Date: 2020-05-27 08:02:57.264315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e019922d64'
down_revision = 'ba9443cb4078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'People', ['user_id'])
    op.create_foreign_key(None, 'Activity', 'People', ['person_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'People', type_='unique')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    # ### end Alembic commands ###
