"""empty message

Revision ID: ba9443cb4078
Revises: cf6338cfa053
Create Date: 2020-05-10 11:13:22.562414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9443cb4078'
down_revision = 'cf6338cfa053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('address', sa.String(), nullable=True))
    op.add_column('People', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('People', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('People', sa.Column('email', sa.String(), nullable=True))
    op.add_column('People', sa.Column('pin_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'pin_code')
    op.drop_column('People', 'email')
    op.drop_column('People', 'created_by')
    op.drop_column('People', 'contact')
    op.drop_column('People', 'address')
    # ### end Alembic commands ###
