"""empty message

Revision ID: cf6338cfa053
Revises: 22fa9ed1461d
Create Date: 2020-05-06 01:47:10.773934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6338cfa053'
down_revision = '22fa9ed1461d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'User', 'License', ['email'], ['user_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    # ### end Alembic commands ###
