"""empty message

Revision ID: d396868947a4
Revises: 1dfb3b1dedb0
Create Date: 2020-04-26 20:43:39.175666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd396868947a4'
down_revision = '1dfb3b1dedb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Activity', 'User', ['user_id'], ['id'])
    op.add_column('License', sa.Column('app_code', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'License', 'User', ['user_id'], ['id'])
    op.add_column('People', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'People', ['aadhar_id'])
    op.create_unique_constraint(None, 'People', ['username'])
    op.create_foreign_key(None, 'People', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'People', type_='foreignkey')
    op.drop_constraint(None, 'People', type_='unique')
    op.drop_constraint(None, 'People', type_='unique')
    op.drop_column('People', 'user_id')
    op.drop_constraint(None, 'License', type_='foreignkey')
    op.drop_column('License', 'app_code')
    op.drop_constraint(None, 'Activity', type_='foreignkey')
    # ### end Alembic commands ###
