"""empty message

Revision ID: d46823402ce0
Revises: 2c2fcabf747b
Create Date: 2020-04-24 09:37:40.770544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd46823402ce0'
down_revision = '2c2fcabf747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Activity')
    op.add_column('People', sa.Column('aadhar_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'aadhar_id')
    op.create_table('Activity',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Activity_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('check_in', 'check_out', name='activity_type'), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Activity_pkey'),
    sa.UniqueConstraint('user_id', name='Activity_user_id_key')
    )
    # ### end Alembic commands ###
