"""empty message

Revision ID: df3d996fe600
Revises: d396868947a4
Create Date: 2020-04-26 21:22:01.447497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3d996fe600'
down_revision = 'd396868947a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('dob', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'dob')
    # ### end Alembic commands ###
